version: "3.2"

services:

  ui:
    image: laravel:latest
    command: bash -c "cp .env.example .env &&
             composer install &&
             php artisan key:generate &&
             apache2-foreground"
    environment:
      APP_NAME: Sober Sec
      APP_ENV: local
      APP_DEBUG: 1
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_gti619
      DB_USERNAME: admin
      DB_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql
      - redis
    volumes:
      - type: bind
        source: /home/vic/projects/gti619/ui
        target: /var/www/html

  mysql:
    image: mariadb:10.3.7
    environment:
        MYSQL_DATABASE: db_gti619
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql

  redis:
    image: redis:4.0.10
    ports:
      - "6379:6379"

volumes:
  mysql_data:

networks:
  default:
    driver: overlay
    attachable: true
